INSERT INTO CodeTable (ColumnName, CodeValue, Description) VALUES ('WOSType','AAP','Additional Approved WOS')
INSERT INTO CodeTable (ColumnName, CodeValue, Description) VALUES ('WOSType','ADD','Additional WOS')
INSERT INTO CodeTable (ColumnName, CodeValue, Description) VALUES ('WOSType','APR','Intial Approved WOS')
INSERT INTO CodeTable (ColumnName, CodeValue, Description) VALUES ('WOSType','INI','Initial WOS')
INSERT INTO CodeTable (ColumnName, CodeValue, Description) VALUES ('WOSType','REF','Refit WOS')
INSERT INTO CodeTable (ColumnName, CodeValue, Description) VALUES ('CorrespondenceType','Appvd','Approved')
INSERT INTO CodeTable (ColumnName, CodeValue, Description) VALUES ('CorrespondenceType','Clarfy','Clarify')
INSERT INTO CodeTable (ColumnName, CodeValue, Description) VALUES ('CorrespondenceType','Commt','Comment')
INSERT INTO CodeTable (ColumnName, CodeValue, Description) VALUES ('CorrespondenceType','Concur','Concurrence')
INSERT INTO CodeTable (ColumnName, CodeValue, Description) VALUES ('CorrespondenceType','Endrs','Endorsed')
INSERT INTO CodeTable (ColumnName, CodeValue, Description) VALUES ('CorrespondenceType','Fwded','Forwarded')
INSERT INTO CodeTable (ColumnName, CodeValue, Description) VALUES ('CorrespondenceType','INCopy','INote Copy Not Received')
INSERT INTO CodeTable (ColumnName, CodeValue, Description) VALUES ('CorrespondenceType','NotRec','Not Recommended')
INSERT INTO CodeTable (ColumnName, CodeValue, Description) VALUES ('CorrespondenceType','OrdLNo','OrdLNo Not in System')
INSERT INTO CodeTable (ColumnName, CodeValue, Description) VALUES ('CorrespondenceType','OrdNot','Order Not In ILMS')
INSERT INTO CodeTable (ColumnName, CodeValue, Description) VALUES ('CorrespondenceType','OrgINo','Original INote Not Received')
INSERT INTO CodeTable (ColumnName, CodeValue, Description) VALUES ('CorrespondenceType','OrgInv','OriginalInvoiceCopyNotReceived')
INSERT INTO CodeTable (ColumnName, CodeValue, Description) VALUES ('CorrespondenceType','POCopy','Contract/ PO Copy Not Received')
INSERT INTO CodeTable (ColumnName, CodeValue, Description) VALUES ('CorrespondenceType','PkgBrk','PKG Broken')
INSERT INTO CodeTable (ColumnName, CodeValue, Description) VALUES ('CorrespondenceType','Rec','Recommended')
INSERT INTO CodeTable (ColumnName, CodeValue, Description) VALUES ('CorrespondenceType','Rejctd','Rejected')
INSERT INTO CodeTable (ColumnName, CodeValue, Description) VALUES ('CorrespondenceType','Rev','Reviewed')
INSERT INTO CodeTable (ColumnName, CodeValue, Description) VALUES ('CorrespondenceType','Vetted','Vetted')
INSERT INTO CodeTable (ColumnName, CodeValue, Description) VALUES ('CorrespondenceType','WPkgR','Wrong Pkg Received')
INSERT INTO CodeTable (ColumnName, CodeValue, Description) VALUES ('CorrespondenceType','WQtyR','Wrong Qty Received')
